### ISSUE TITLE
HACS support

### ISSUE THREAD

**Issue by dodekaphilist** [newAM/hisensetv_hass#2]
This component seems pretty interesting, however I was not able to get it to run in Home Assistant installed on a Raspberry Pi. Where shall I run the authentication code? Could you update the instructions to make them idiot-proof? 

Also, maybe you could take a look into the [HACS documentation](https://hacs.xyz/docs/developer/start) for proper support for that, as it generally makes custom component installations much easier for users.

**Comment by newAM** [comment]
> Where shall I run the authentication code?

Anywhere, your local desktop / laptop will work, or your home-assistant server.  After the API is authorized it will work from any device.

> Could you update the instructions to make them idiot-proof?

Will do before this issue is closed :+1: 

I will look into HACS, have not heard of this before!

**Comment by dodekaphilist** [comment]
Thanks for the reply. I finally got it to work with the basic functionality.

> I will look into HACS, have not heard of this before!

Probably not the last thing to do, so I am looking forward to the further development.

**Comment by newAM** [comment]
I added HACS support and updated the README.  Unfortunately I got rate-limited by the github API before I could test it out with HACS.  I'll check back later.

**Comment by sym0nd0** [comment]
Hi, I can't find this on HACS, I've tried every search I can think of. Could you take a look when you get chance please?

**Comment by newAM** [comment]
It is not on the HACS mainline - you need to add it as a custom repository, I should make that explicit in the readme.

**Comment by sym0nd0** [comment]
Weird, I tried to add your repo in HACS last night, before making my comment above, and it just errored out. Tried again now, using https://github.com/newAM/hisensetv_hass, and it's worked first time. :/

I can only think it was user error, sorry.
